# Generated by Django 3.1.5 on 2021-01-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0001_initial'),
        ('accounts', '0002_auto_20210131_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tasks',
            field=models.ManyToManyField(null=True, related_name='users', to='taskManager.Task'),
        ),
    ]
